-- SQL Server schema base para Geo URP (RF-001..RF-015)
CREATE TABLE Roles (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(100) NOT NULL UNIQUE, Description NVARCHAR(250) NULL, IsActive BIT NOT NULL DEFAULT 1, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE Users (Id INT IDENTITY PRIMARY KEY, FullName NVARCHAR(180) NOT NULL, Email NVARCHAR(180) NOT NULL UNIQUE, PasswordHash NVARCHAR(300) NOT NULL, IsActive BIT NOT NULL DEFAULT 1, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
CREATE TABLE UserRoles (UserId INT NOT NULL, RoleId INT NOT NULL, CONSTRAINT PK_UserRoles PRIMARY KEY (UserId, RoleId), CONSTRAINT FK_UserRoles_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE, CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE);

CREATE TABLE BoardMembers (Id INT IDENTITY PRIMARY KEY, FullName NVARCHAR(180) NOT NULL, Position NVARCHAR(150) NOT NULL, PhotoUrl NVARCHAR(500) NULL, Bio NVARCHAR(1000) NULL, SortOrder INT NOT NULL DEFAULT 0, IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE Events (Id INT IDENTITY PRIMARY KEY, Title NVARCHAR(220) NOT NULL, Description NVARCHAR(MAX) NULL, StartAt DATETIME2 NOT NULL, EndAt DATETIME2 NOT NULL, Location NVARCHAR(200) NULL, IsPublic BIT NOT NULL DEFAULT 1, CONSTRAINT CK_Events_DateRange CHECK (EndAt >= StartAt));

CREATE TABLE ResearchCategories (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(150) NOT NULL UNIQUE, IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE ExamCategories (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(150) NOT NULL UNIQUE, IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE BookCategories (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(150) NOT NULL UNIQUE, IsActive BIT NOT NULL DEFAULT 1);

CREATE TABLE Researches (Id INT IDENTITY PRIMARY KEY, Title NVARCHAR(250) NOT NULL, Summary NVARCHAR(MAX) NULL, FileUrl NVARCHAR(500) NULL, CategoryId INT NOT NULL FOREIGN KEY REFERENCES ResearchCategories(Id), PublishedAt DATETIME2 NULL, IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE Exams (Id INT IDENTITY PRIMARY KEY, Title NVARCHAR(250) NOT NULL, Description NVARCHAR(MAX) NULL, ExamDate DATETIME2 NULL, FileUrl NVARCHAR(500) NULL, CategoryId INT NOT NULL FOREIGN KEY REFERENCES ExamCategories(Id), IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE Books (Id INT IDENTITY PRIMARY KEY, Title NVARCHAR(250) NOT NULL, Author NVARCHAR(180) NULL, Editorial NVARCHAR(180) NULL, [Year] INT NULL, FileUrl NVARCHAR(500) NULL, CategoryId INT NOT NULL FOREIGN KEY REFERENCES BookCategories(Id), IsActive BIT NOT NULL DEFAULT 1);

CREATE TABLE ContactMessages (Id INT IDENTITY PRIMARY KEY, FullName NVARCHAR(180) NOT NULL, Email NVARCHAR(180) NOT NULL, Subject NVARCHAR(220) NULL, Message NVARCHAR(MAX) NOT NULL, IsRead BIT NOT NULL DEFAULT 0, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
